const PORT = 'PORT';
const MYSQL_HOST = 'MYSQL_HOST';
const MYSQL_PORT = 'MYSQL_PORT';
const MYSQL_USER = 'MYSQL_USER';
const MYSQL_PASS = 'MYSQL_PASS';
const MYSQL_DB = 'MYSQL_DB';
const JWT_SECRET = 'JWT_SECRET';
export {
  PORT,
  MYSQL_HOST,
  MYSQL_PORT,
  MYSQL_USER,
  MYSQL_PASS,
  MYSQL_DB,
  JWT_SECRET,
};
